version: '3.8'
services:
  mongo:
    image: mongo:latest
    command: ["mongod", "--auth"]
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

volumes:
  mongo_data:
    driver: local
