services:
  mongo:
    image: mongo:4.4.6
    command: ["mongod", "--auth"]
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: always


  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"    # Puerto para conexiones de cliente
      - "15672:15672"  # Puerto para la consola de administración de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local
